<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.telefonica.coco.tap</groupId>
        <artifactId>tap-parent</artifactId>
        <version>4.4.5-15</version>
    </parent>
    <groupId>com.telefonica.bst3.srv.nuc</groupId>
    <artifactId>srv-nuc-jee-PruebaGitHub</artifactId>
    <version>4.0.0-SNAPSHOT</version>
    <name>srv-nuc-jee-PruebaGitHub</name>
    <packaging>jar</packaging>
    <url>http://www.telefonica.es</url>
    <properties>
        <aplicacion>bst3</aplicacion>
        <tipo.activo>srv-nuc-jee</tipo.activo>
        <revision>1</revision>
        <entrega>1</entrega>
        <aris.id>2cd73c22-27d2-11ea-2291-005056ad40c0</aris.id>
        <database.id>1706478230,0,106</database.id>
        <tecnologia.implementacion>JEE</tecnologia.implementacion>
        <app.main-class>com.telefonica.bst3.srv.nuc.pruebagithub.PruebaGitHubApplication</app.main-class>
        <weblogic.context-root>/bst3/srv-nuc-PruebaGitHub/v4</weblogic.context-root>
        <endpoint.resource>uddi:bst3.srv-nuc-PruebaGitHub-R-v4=/bst3/srv-nuc-PruebaGitHub/v4/resources</endpoint.resource>
        <endpoint.resource-exp>uddi:bst3.srv-exp-PruebaGitHub-R-v4=/bst3/srv-nuc-PruebaGitHub/v4/resources</endpoint.resource-exp>
        <endpoint.webservice>uddi:bst3.srv-nuc-PruebaGitHub-v4=/bst3/srv-nuc-PruebaGitHub/v4/services/endpoint,/publicsvn/PUBLICO/1_VigentesDESA/_OLA2/BST3/srv-nuc-jee/trunk/srv-nuc-jee-PruebaGitHub/wsdl/srv-nuc-PruebaGitHub-v4.wsdl</endpoint.webservice>
        <endpoint.webservice-exp>uddi:bst3.srv-exp-PruebaGitHub-v4=/bst3/srv-nuc-PruebaGitHub/v4/services/endpoint,/publicsvn/PUBLICO/1_VigentesDESA/_OLA2/BST3/srv-nuc-jee/trunk/srv-nuc-jee-PruebaGitHub/wsdl/srv-nuc-PruebaGitHub-v4.wsdl</endpoint.webservice-exp>
    </properties>
    <dependencies>
        <!-- **************** Infrastructure **************** -->
        <dependency>
            <groupId>com.telefonica.coco.tap</groupId>
            <artifactId>tap-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.telefonica.coco.tap</groupId>
            <artifactId>tap-starter-web-services</artifactId>
        </dependency>
        <dependency>
            <groupId>com.telefonica.coco.tap</groupId>
            <artifactId>tap-starter-data</artifactId>
        </dependency>
        <dependency>
            <groupId>com.telefonica.coco.tap</groupId>
            <artifactId>tap-starter-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.telefonica.coco.tap</groupId>
            <artifactId>tap-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!-- **************** Application-specific **************** -->
        <dependency>
            <groupId>com.telefonica.bst3.model</groupId>
            <artifactId>model-bst3</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
